// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV7PfWX-CW6OBKOT-_CbBI6MQG3wjQADQ',
    appId: '1:198650548738:web:1b1c3032c5da6d4ebacd1b',
    messagingSenderId: '198650548738',
    projectId: 'vconekt-2f601',
    authDomain: 'vconekt-2f601.firebaseapp.com',
    storageBucket: 'vconekt-2f601.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHFIT-UQ74I5pmxpSA-xjDI7eXrcbHzlk',
    appId: '1:198650548738:android:35a6e037d91765f0bacd1b',
    messagingSenderId: '198650548738',
    projectId: 'vconekt-2f601',
    storageBucket: 'vconekt-2f601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpQheGqZKoE-H6bAT0pU5IBqP-3gR8h4M',
    appId: '1:198650548738:ios:009b173acf22f314bacd1b',
    messagingSenderId: '198650548738',
    projectId: 'vconekt-2f601',
    storageBucket: 'vconekt-2f601.appspot.com',
    iosBundleId: 'com.example.vconektInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpQheGqZKoE-H6bAT0pU5IBqP-3gR8h4M',
    appId: '1:198650548738:ios:009b173acf22f314bacd1b',
    messagingSenderId: '198650548738',
    projectId: 'vconekt-2f601',
    storageBucket: 'vconekt-2f601.appspot.com',
    iosBundleId: 'com.example.vconektInterview',
  );
}
